
package com.z2systems.schemas.neonws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T17:30:59.377Z
 * Generated source version: 3.1.11
 * 
 */
public final class AccountService_AccountPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.z2systems.com/schemas/neonws/", "Neonws");

    private AccountService_AccountPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Neonws.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Neonws ss = new Neonws(wsdlURL, SERVICE_NAME);
        AccountService port = ss.getAccountPort();  
        
        {
        System.out.println("Invoking removeAddress...");
        com.z2systems.schemas.account.RemoveAddressRequest _removeAddress_request = null;
        com.z2systems.schemas.account.RemoveAddressResponse _removeAddress__return = port.removeAddress(_removeAddress_request);
        System.out.println("removeAddress.result=" + _removeAddress__return);


        }
        {
        System.out.println("Invoking listSources...");
        com.z2systems.schemas.account.ListSourcesRequest _listSources_request = null;
        com.z2systems.schemas.account.ListSourcesResponse _listSources__return = port.listSources(_listSources_request);
        System.out.println("listSources.result=" + _listSources__return);


        }
        {
        System.out.println("Invoking updateActivity...");
        com.z2systems.schemas.account.UpdateActivityRequest _updateActivity_request = null;
        com.z2systems.schemas.account.UpdateActivityResponse _updateActivity__return = port.updateActivity(_updateActivity_request);
        System.out.println("updateActivity.result=" + _updateActivity__return);


        }
        {
        System.out.println("Invoking retrieveActivity...");
        com.z2systems.schemas.account.RetrieveActivityRequest _retrieveActivity_request = null;
        com.z2systems.schemas.account.RetrieveActivityResponse _retrieveActivity__return = port.retrieveActivity(_retrieveActivity_request);
        System.out.println("retrieveActivity.result=" + _retrieveActivity__return);


        }
        {
        System.out.println("Invoking editIndividualAccount...");
        com.z2systems.schemas.account.EditIndividualAccountRequest _editIndividualAccount_request = null;
        com.z2systems.schemas.account.EditIndividualAccountResponse _editIndividualAccount__return = port.editIndividualAccount(_editIndividualAccount_request);
        System.out.println("editIndividualAccount.result=" + _editIndividualAccount__return);


        }
        {
        System.out.println("Invoking addAddress...");
        com.z2systems.schemas.account.AddAddressRequest _addAddress_request = null;
        com.z2systems.schemas.account.AddAddressResponse _addAddress__return = port.addAddress(_addAddress_request);
        System.out.println("addAddress.result=" + _addAddress__return);


        }
        {
        System.out.println("Invoking listIndividualTypes...");
        com.z2systems.schemas.account.ListIndividualTypesRequest _listIndividualTypes_request = null;
        com.z2systems.schemas.account.ListIndividualTypesResponse _listIndividualTypes__return = port.listIndividualTypes(_listIndividualTypes_request);
        System.out.println("listIndividualTypes.result=" + _listIndividualTypes__return);


        }
        {
        System.out.println("Invoking addToFavoriteAccounts...");
        com.z2systems.schemas.account.AddToFavoirteAccountsRequest _addToFavoriteAccounts_request = null;
        com.z2systems.schemas.account.AddToFavoriteAccountsResponse _addToFavoriteAccounts__return = port.addToFavoriteAccounts(_addToFavoriteAccounts_request);
        System.out.println("addToFavoriteAccounts.result=" + _addToFavoriteAccounts__return);


        }
        {
        System.out.println("Invoking editOrganizationAccount...");
        com.z2systems.schemas.account.EditOrganizationAccountRequest _editOrganizationAccount_request = null;
        com.z2systems.schemas.account.EditOrganizationAccountResponse _editOrganizationAccount__return = port.editOrganizationAccount(_editOrganizationAccount_request);
        System.out.println("editOrganizationAccount.result=" + _editOrganizationAccount__return);


        }
        {
        System.out.println("Invoking listAccountsByKeywordSearch...");
        com.z2systems.schemas.account.ListAccountsByKeywordSearchRequest _listAccountsByKeywordSearch_request = null;
        com.z2systems.schemas.account.ListAccountsByKeywordSearchResponse _listAccountsByKeywordSearch__return = port.listAccountsByKeywordSearch(_listAccountsByKeywordSearch_request);
        System.out.println("listAccountsByKeywordSearch.result=" + _listAccountsByKeywordSearch__return);


        }
        {
        System.out.println("Invoking removeActivity...");
        com.z2systems.schemas.account.RemoveActivityRequest _removeActivity_request = null;
        com.z2systems.schemas.account.RemoveActivityResponse _removeActivity__return = port.removeActivity(_removeActivity_request);
        System.out.println("removeActivity.result=" + _removeActivity__return);


        }
        {
        System.out.println("Invoking createOrganizationAccount...");
        com.z2systems.schemas.account.CreateOrganizationAccountRequest _createOrganizationAccount_request = null;
        com.z2systems.schemas.account.CreateOrganizationAccountResponse _createOrganizationAccount__return = port.createOrganizationAccount(_createOrganizationAccount_request);
        System.out.println("createOrganizationAccount.result=" + _createOrganizationAccount__return);


        }
        {
        System.out.println("Invoking updateHouseHoldPrimary...");
        com.z2systems.schemas.account.UpdateHouseHoldPrimaryRequest _updateHouseHoldPrimary_request = null;
        com.z2systems.schemas.account.UpdateHouseHoldPrimaryResponse _updateHouseHoldPrimary__return = port.updateHouseHoldPrimary(_updateHouseHoldPrimary_request);
        System.out.println("updateHouseHoldPrimary.result=" + _updateHouseHoldPrimary__return);


        }
        {
        System.out.println("Invoking addIndividualToHouseHold...");
        com.z2systems.schemas.account.AddIndividualToHouseHoldRequest _addIndividualToHouseHold_request = null;
        com.z2systems.schemas.account.AddIndividualToHouseHoldResponse _addIndividualToHouseHold__return = port.addIndividualToHouseHold(_addIndividualToHouseHold_request);
        System.out.println("addIndividualToHouseHold.result=" + _addIndividualToHouseHold__return);


        }
        {
        System.out.println("Invoking updateAddress...");
        com.z2systems.schemas.account.UpdateAddressRequest _updateAddress_request = null;
        com.z2systems.schemas.account.UpdateAddressResponse _updateAddress__return = port.updateAddress(_updateAddress_request);
        System.out.println("updateAddress.result=" + _updateAddress__return);


        }
        {
        System.out.println("Invoking removeIndividualFromHouseHold...");
        com.z2systems.schemas.account.RemoveIndividualFromHouseHoldRequest _removeIndividualFromHouseHold_request = null;
        com.z2systems.schemas.account.RemoveIndividualFromHouseHoldResponse _removeIndividualFromHouseHold__return = port.removeIndividualFromHouseHold(_removeIndividualFromHouseHold_request);
        System.out.println("removeIndividualFromHouseHold.result=" + _removeIndividualFromHouseHold__return);


        }
        {
        System.out.println("Invoking linkIndividualToOrganization...");
        com.z2systems.schemas.account.LinkIndividualToOrganizationRequest _linkIndividualToOrganization_request = null;
        com.z2systems.schemas.account.LinkIndividualToOrganizationResponse _linkIndividualToOrganization__return = port.linkIndividualToOrganization(_linkIndividualToOrganization_request);
        System.out.println("linkIndividualToOrganization.result=" + _linkIndividualToOrganization__return);


        }
        {
        System.out.println("Invoking listCountries...");
        com.z2systems.schemas.account.ListCountriesRequest _listCountries_request = null;
        com.z2systems.schemas.account.ListCountriesResponse _listCountries__return = port.listCountries(_listCountries_request);
        System.out.println("listCountries.result=" + _listCountries__return);


        }
        {
        System.out.println("Invoking listFavoriteAccounts...");
        com.z2systems.schemas.account.ListFavoriteAccountsRequest _listFavoriteAccounts_request = null;
        com.z2systems.schemas.account.ListFavoriteAccountsResponse _listFavoriteAccounts__return = port.listFavoriteAccounts(_listFavoriteAccounts_request);
        System.out.println("listFavoriteAccounts.result=" + _listFavoriteAccounts__return);


        }
        {
        System.out.println("Invoking removeFromFavoriteAccounts...");
        com.z2systems.schemas.account.RemoveFromFavoriteAccountsRequest _removeFromFavoriteAccounts_request = null;
        com.z2systems.schemas.account.RemoveFromFavoriteAccountsResponse _removeFromFavoriteAccounts__return = port.removeFromFavoriteAccounts(_removeFromFavoriteAccounts_request);
        System.out.println("removeFromFavoriteAccounts.result=" + _removeFromFavoriteAccounts__return);


        }
        {
        System.out.println("Invoking retrieveIndividualAccount...");
        com.z2systems.schemas.account.RetrieveIndividualAccountRequest _retrieveIndividualAccount_request = null;
        com.z2systems.schemas.account.RetrieveIndividualAccountResponse _retrieveIndividualAccount__return = port.retrieveIndividualAccount(_retrieveIndividualAccount_request);
        System.out.println("retrieveIndividualAccount.result=" + _retrieveIndividualAccount__return);


        }
        {
        System.out.println("Invoking syncActivities...");
        com.z2systems.schemas.account.SyncActivitiesRequest _syncActivities_request = null;
        com.z2systems.schemas.account.SyncActivitiesResponse _syncActivities__return = port.syncActivities(_syncActivities_request);
        System.out.println("syncActivities.result=" + _syncActivities__return);


        }
        {
        System.out.println("Invoking listStates...");
        com.z2systems.schemas.account.ListStatesRequest _listStates_request = null;
        com.z2systems.schemas.account.ListStatesResponse _listStates__return = port.listStates(_listStates_request);
        System.out.println("listStates.result=" + _listStates__return);


        }
        {
        System.out.println("Invoking createIndividualAccount...");
        com.z2systems.schemas.account.CreateIndividualAccountRequest _createIndividualAccount_request = null;
        com.z2systems.schemas.account.CreateIndividualAccountResponse _createIndividualAccount__return = port.createIndividualAccount(_createIndividualAccount_request);
        System.out.println("createIndividualAccount.result=" + _createIndividualAccount__return);


        }
        {
        System.out.println("Invoking listHouseHolds...");
        com.z2systems.schemas.account.ListHouseHoldsRequest _listHouseHolds_request = null;
        com.z2systems.schemas.account.ListHouseHoldsResponse _listHouseHolds__return = port.listHouseHolds(_listHouseHolds_request);
        System.out.println("listHouseHolds.result=" + _listHouseHolds__return);


        }
        {
        System.out.println("Invoking listOrganizationContacts...");
        com.z2systems.schemas.account.ListOrganizationContactsRequest _listOrganizationContacts_request = null;
        com.z2systems.schemas.account.ListOrganizationContactsResponse _listOrganizationContacts__return = port.listOrganizationContacts(_listOrganizationContacts_request);
        System.out.println("listOrganizationContacts.result=" + _listOrganizationContacts__return);


        }
        {
        System.out.println("Invoking updateIndividualAccount...");
        com.z2systems.schemas.account.UpdateIndividualAccountRequest _updateIndividualAccount_request = null;
        com.z2systems.schemas.account.UpdateIndividualAccountResponse _updateIndividualAccount__return = port.updateIndividualAccount(_updateIndividualAccount_request);
        System.out.println("updateIndividualAccount.result=" + _updateIndividualAccount__return);


        }
        {
        System.out.println("Invoking addActivity...");
        com.z2systems.schemas.account.AddActivityRequest _addActivity_request = null;
        com.z2systems.schemas.account.AddActivityResponse _addActivity__return = port.addActivity(_addActivity_request);
        System.out.println("addActivity.result=" + _addActivity__return);


        }
        {
        System.out.println("Invoking updateHouseHold...");
        com.z2systems.schemas.account.UpdateHouseHoldRequest _updateHouseHold_request = null;
        com.z2systems.schemas.account.UpdateHouseHoldResponse _updateHouseHold__return = port.updateHouseHold(_updateHouseHold_request);
        System.out.println("updateHouseHold.result=" + _updateHouseHold__return);


        }
        {
        System.out.println("Invoking removeIndividualFromOrganization...");
        com.z2systems.schemas.account.RemoveIndividualFromOrganizationRequest _removeIndividualFromOrganization_request = null;
        com.z2systems.schemas.account.RemoveIndividualFromOrganizationResponse _removeIndividualFromOrganization__return = port.removeIndividualFromOrganization(_removeIndividualFromOrganization_request);
        System.out.println("removeIndividualFromOrganization.result=" + _removeIndividualFromOrganization__return);


        }
        {
        System.out.println("Invoking listAccountsByDefault...");
        com.z2systems.schemas.account.ListAccountsByDefaultRequest _listAccountsByDefault_request = null;
        com.z2systems.schemas.account.ListAccountsByDefaultResponse _listAccountsByDefault__return = port.listAccountsByDefault(_listAccountsByDefault_request);
        System.out.println("listAccountsByDefault.result=" + _listAccountsByDefault__return);


        }
        {
        System.out.println("Invoking listAddressTypes...");
        com.z2systems.schemas.account.ListAddressTypesRequest _listAddressTypes_request = null;
        com.z2systems.schemas.account.ListAddressTypesResponse _listAddressTypes__return = port.listAddressTypes(_listAddressTypes_request);
        System.out.println("listAddressTypes.result=" + _listAddressTypes__return);


        }
        {
        System.out.println("Invoking listGenders...");
        com.z2systems.schemas.account.ListGendersRequest _listGenders_request = null;
        com.z2systems.schemas.account.ListGendersResponse _listGenders__return = port.listGenders(_listGenders_request);
        System.out.println("listGenders.result=" + _listGenders__return);


        }
        {
        System.out.println("Invoking deleteHouseHold...");
        com.z2systems.schemas.account.DeleteHouseHoldRequest _deleteHouseHold_request = null;
        com.z2systems.schemas.account.DeleteHouseHoldResponse _deleteHouseHold__return = port.deleteHouseHold(_deleteHouseHold_request);
        System.out.println("deleteHouseHold.result=" + _deleteHouseHold__return);


        }
        {
        System.out.println("Invoking retrieveTransactionStats...");
        com.z2systems.schemas.account.RetrieveTransactionStatsRequest _retrieveTransactionStats_request = null;
        com.z2systems.schemas.account.RetrieveTransactionStatsResponse _retrieveTransactionStats__return = port.retrieveTransactionStats(_retrieveTransactionStats_request);
        System.out.println("retrieveTransactionStats.result=" + _retrieveTransactionStats__return);


        }
        {
        System.out.println("Invoking listActivities...");
        com.z2systems.schemas.account.ListActivitiesRequest _listActivities_request = null;
        com.z2systems.schemas.account.ListActivitiesResponse _listActivities__return = port.listActivities(_listActivities_request);
        System.out.println("listActivities.result=" + _listActivities__return);


        }
        {
        System.out.println("Invoking syncAccounts...");
        com.z2systems.schemas.account.SyncAccountsRequest _syncAccounts_request = null;
        com.z2systems.schemas.account.SyncAccountsResponse _syncAccounts__return = port.syncAccounts(_syncAccounts_request);
        System.out.println("syncAccounts.result=" + _syncAccounts__return);


        }
        {
        System.out.println("Invoking updateOrganizationAccount...");
        com.z2systems.schemas.account.UpdateOrganizationAccountRequest _updateOrganizationAccount_request = null;
        com.z2systems.schemas.account.UpdateOrganizationAccountResponse _updateOrganizationAccount__return = port.updateOrganizationAccount(_updateOrganizationAccount_request);
        System.out.println("updateOrganizationAccount.result=" + _updateOrganizationAccount__return);


        }
        {
        System.out.println("Invoking listOrganizationTypes...");
        com.z2systems.schemas.account.ListOrganizationTypesRequest _listOrganizationTypes_request = null;
        com.z2systems.schemas.account.ListOrganizationTypesResponse _listOrganizationTypes__return = port.listOrganizationTypes(_listOrganizationTypes_request);
        System.out.println("listOrganizationTypes.result=" + _listOrganizationTypes__return);


        }
        {
        System.out.println("Invoking createHouseHold...");
        com.z2systems.schemas.account.CreateHouseHoldRequest _createHouseHold_request = null;
        com.z2systems.schemas.account.CreateHouseHoldResponse _createHouseHold__return = port.createHouseHold(_createHouseHold_request);
        System.out.println("createHouseHold.result=" + _createHouseHold__return);


        }
        {
        System.out.println("Invoking retrieveOrganizationAccount...");
        com.z2systems.schemas.account.RetrieveOrganizationAccountRequest _retrieveOrganizationAccount_request = null;
        com.z2systems.schemas.account.RetrieveOrganizationAccountResponse _retrieveOrganizationAccount__return = port.retrieveOrganizationAccount(_retrieveOrganizationAccount_request);
        System.out.println("retrieveOrganizationAccount.result=" + _retrieveOrganizationAccount__return);


        }
        {
        System.out.println("Invoking listPrefixes...");
        com.z2systems.schemas.account.ListPrefixesRequest _listPrefixes_request = null;
        com.z2systems.schemas.account.ListPrefixesResponse _listPrefixes__return = port.listPrefixes(_listPrefixes_request);
        System.out.println("listPrefixes.result=" + _listPrefixes__return);


        }
        {
        System.out.println("Invoking listAccountsBySearchCriteria...");
        com.z2systems.schemas.account.ListAccountsBySearchCriteriaRequest _listAccountsBySearchCriteria_request = null;
        com.z2systems.schemas.account.ListAccountsBySearchCriteriaResponse _listAccountsBySearchCriteria__return = port.listAccountsBySearchCriteria(_listAccountsBySearchCriteria_request);
        System.out.println("listAccountsBySearchCriteria.result=" + _listAccountsBySearchCriteria__return);


        }
        {
        System.out.println("Invoking listActivityStatus...");
        com.z2systems.schemas.account.ListActivityStatusRequest _listActivityStatus_request = null;
        com.z2systems.schemas.account.ListActivityStatusResponse _listActivityStatus__return = port.listActivityStatus(_listActivityStatus_request);
        System.out.println("listActivityStatus.result=" + _listActivityStatus__return);


        }
        {
        System.out.println("Invoking listSystemUsers...");
        com.z2systems.schemas.account.ListSystemUsersRequest _listSystemUsers_request = null;
        com.z2systems.schemas.account.ListSystemUsersResponse _listSystemUsers__return = port.listSystemUsers(_listSystemUsers_request);
        System.out.println("listSystemUsers.result=" + _listSystemUsers__return);


        }
        {
        System.out.println("Invoking listRelationTypes...");
        com.z2systems.schemas.account.ListRelationTypesRequest _listRelationTypes_request = null;
        com.z2systems.schemas.account.ListRelationTypesResponse _listRelationTypes__return = port.listRelationTypes(_listRelationTypes_request);
        System.out.println("listRelationTypes.result=" + _listRelationTypes__return);


        }
        {
        System.out.println("Invoking listAccounts...");
        com.z2systems.schemas.account.ListAccountsRequest _listAccounts_request = null;
        com.z2systems.schemas.account.ListAccountsResponse _listAccounts__return = port.listAccounts(_listAccounts_request);
        System.out.println("listAccounts.result=" + _listAccounts__return);


        }

        System.exit(0);
    }

}
