
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.z2systems.schemas.neonws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T17:30:59.549Z
 * Generated source version: 3.1.11
 * 
 */

@WebService(
                      serviceName = "Neonws",
                      portName = "AccountPort",
                      targetNamespace = "http://www.z2systems.com/schemas/neonws/",
                      wsdlLocation = "file:../wsdl/definitions.wsdl",
                      endpointInterface = "com.z2systems.schemas.neonws.AccountService")
                      
public class AccountPortImpl implements AccountService {

    private static final Logger LOG = Logger.getLogger(AccountPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#removeAddress(com.z2systems.schemas.account.RemoveAddressRequest request)*
     */
    public com.z2systems.schemas.account.RemoveAddressResponse removeAddress(com.z2systems.schemas.account.RemoveAddressRequest request) { 
        LOG.info("Executing operation removeAddress");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.RemoveAddressResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listSources(com.z2systems.schemas.account.ListSourcesRequest request)*
     */
    public com.z2systems.schemas.account.ListSourcesResponse listSources(com.z2systems.schemas.account.ListSourcesRequest request) { 
        LOG.info("Executing operation listSources");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListSourcesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#updateActivity(com.z2systems.schemas.account.UpdateActivityRequest request)*
     */
    public com.z2systems.schemas.account.UpdateActivityResponse updateActivity(com.z2systems.schemas.account.UpdateActivityRequest request) { 
        LOG.info("Executing operation updateActivity");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.UpdateActivityResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#retrieveActivity(com.z2systems.schemas.account.RetrieveActivityRequest request)*
     */
    public com.z2systems.schemas.account.RetrieveActivityResponse retrieveActivity(com.z2systems.schemas.account.RetrieveActivityRequest request) { 
        LOG.info("Executing operation retrieveActivity");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.RetrieveActivityResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#editIndividualAccount(com.z2systems.schemas.account.EditIndividualAccountRequest request)*
     */
    public com.z2systems.schemas.account.EditIndividualAccountResponse editIndividualAccount(com.z2systems.schemas.account.EditIndividualAccountRequest request) { 
        LOG.info("Executing operation editIndividualAccount");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.EditIndividualAccountResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#addAddress(com.z2systems.schemas.account.AddAddressRequest request)*
     */
    public com.z2systems.schemas.account.AddAddressResponse addAddress(com.z2systems.schemas.account.AddAddressRequest request) { 
        LOG.info("Executing operation addAddress");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.AddAddressResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listIndividualTypes(com.z2systems.schemas.account.ListIndividualTypesRequest request)*
     */
    public com.z2systems.schemas.account.ListIndividualTypesResponse listIndividualTypes(com.z2systems.schemas.account.ListIndividualTypesRequest request) { 
        LOG.info("Executing operation listIndividualTypes");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListIndividualTypesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#addToFavoriteAccounts(com.z2systems.schemas.account.AddToFavoirteAccountsRequest request)*
     */
    public com.z2systems.schemas.account.AddToFavoriteAccountsResponse addToFavoriteAccounts(com.z2systems.schemas.account.AddToFavoirteAccountsRequest request) { 
        LOG.info("Executing operation addToFavoriteAccounts");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.AddToFavoriteAccountsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#editOrganizationAccount(com.z2systems.schemas.account.EditOrganizationAccountRequest request)*
     */
    public com.z2systems.schemas.account.EditOrganizationAccountResponse editOrganizationAccount(com.z2systems.schemas.account.EditOrganizationAccountRequest request) { 
        LOG.info("Executing operation editOrganizationAccount");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.EditOrganizationAccountResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listAccountsByKeywordSearch(com.z2systems.schemas.account.ListAccountsByKeywordSearchRequest request)*
     */
    public com.z2systems.schemas.account.ListAccountsByKeywordSearchResponse listAccountsByKeywordSearch(com.z2systems.schemas.account.ListAccountsByKeywordSearchRequest request) { 
        LOG.info("Executing operation listAccountsByKeywordSearch");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListAccountsByKeywordSearchResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#removeActivity(com.z2systems.schemas.account.RemoveActivityRequest request)*
     */
    public com.z2systems.schemas.account.RemoveActivityResponse removeActivity(com.z2systems.schemas.account.RemoveActivityRequest request) { 
        LOG.info("Executing operation removeActivity");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.RemoveActivityResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#createOrganizationAccount(com.z2systems.schemas.account.CreateOrganizationAccountRequest request)*
     */
    public com.z2systems.schemas.account.CreateOrganizationAccountResponse createOrganizationAccount(com.z2systems.schemas.account.CreateOrganizationAccountRequest request) { 
        LOG.info("Executing operation createOrganizationAccount");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.CreateOrganizationAccountResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#updateHouseHoldPrimary(com.z2systems.schemas.account.UpdateHouseHoldPrimaryRequest request)*
     */
    public com.z2systems.schemas.account.UpdateHouseHoldPrimaryResponse updateHouseHoldPrimary(com.z2systems.schemas.account.UpdateHouseHoldPrimaryRequest request) { 
        LOG.info("Executing operation updateHouseHoldPrimary");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.UpdateHouseHoldPrimaryResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#addIndividualToHouseHold(com.z2systems.schemas.account.AddIndividualToHouseHoldRequest request)*
     */
    public com.z2systems.schemas.account.AddIndividualToHouseHoldResponse addIndividualToHouseHold(com.z2systems.schemas.account.AddIndividualToHouseHoldRequest request) { 
        LOG.info("Executing operation addIndividualToHouseHold");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.AddIndividualToHouseHoldResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#updateAddress(com.z2systems.schemas.account.UpdateAddressRequest request)*
     */
    public com.z2systems.schemas.account.UpdateAddressResponse updateAddress(com.z2systems.schemas.account.UpdateAddressRequest request) { 
        LOG.info("Executing operation updateAddress");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.UpdateAddressResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#removeIndividualFromHouseHold(com.z2systems.schemas.account.RemoveIndividualFromHouseHoldRequest request)*
     */
    public com.z2systems.schemas.account.RemoveIndividualFromHouseHoldResponse removeIndividualFromHouseHold(com.z2systems.schemas.account.RemoveIndividualFromHouseHoldRequest request) { 
        LOG.info("Executing operation removeIndividualFromHouseHold");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.RemoveIndividualFromHouseHoldResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#linkIndividualToOrganization(com.z2systems.schemas.account.LinkIndividualToOrganizationRequest request)*
     */
    public com.z2systems.schemas.account.LinkIndividualToOrganizationResponse linkIndividualToOrganization(com.z2systems.schemas.account.LinkIndividualToOrganizationRequest request) { 
        LOG.info("Executing operation linkIndividualToOrganization");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.LinkIndividualToOrganizationResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listCountries(com.z2systems.schemas.account.ListCountriesRequest request)*
     */
    public com.z2systems.schemas.account.ListCountriesResponse listCountries(com.z2systems.schemas.account.ListCountriesRequest request) { 
        LOG.info("Executing operation listCountries");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListCountriesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listFavoriteAccounts(com.z2systems.schemas.account.ListFavoriteAccountsRequest request)*
     */
    public com.z2systems.schemas.account.ListFavoriteAccountsResponse listFavoriteAccounts(com.z2systems.schemas.account.ListFavoriteAccountsRequest request) { 
        LOG.info("Executing operation listFavoriteAccounts");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListFavoriteAccountsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#removeFromFavoriteAccounts(com.z2systems.schemas.account.RemoveFromFavoriteAccountsRequest request)*
     */
    public com.z2systems.schemas.account.RemoveFromFavoriteAccountsResponse removeFromFavoriteAccounts(com.z2systems.schemas.account.RemoveFromFavoriteAccountsRequest request) { 
        LOG.info("Executing operation removeFromFavoriteAccounts");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.RemoveFromFavoriteAccountsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#retrieveIndividualAccount(com.z2systems.schemas.account.RetrieveIndividualAccountRequest request)*
     */
    public com.z2systems.schemas.account.RetrieveIndividualAccountResponse retrieveIndividualAccount(com.z2systems.schemas.account.RetrieveIndividualAccountRequest request) { 
        LOG.info("Executing operation retrieveIndividualAccount");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.RetrieveIndividualAccountResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#syncActivities(com.z2systems.schemas.account.SyncActivitiesRequest request)*
     */
    public com.z2systems.schemas.account.SyncActivitiesResponse syncActivities(com.z2systems.schemas.account.SyncActivitiesRequest request) { 
        LOG.info("Executing operation syncActivities");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.SyncActivitiesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listStates(com.z2systems.schemas.account.ListStatesRequest request)*
     */
    public com.z2systems.schemas.account.ListStatesResponse listStates(com.z2systems.schemas.account.ListStatesRequest request) { 
        LOG.info("Executing operation listStates");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListStatesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#createIndividualAccount(com.z2systems.schemas.account.CreateIndividualAccountRequest request)*
     */
    public com.z2systems.schemas.account.CreateIndividualAccountResponse createIndividualAccount(com.z2systems.schemas.account.CreateIndividualAccountRequest request) { 
        LOG.info("Executing operation createIndividualAccount");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.CreateIndividualAccountResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listHouseHolds(com.z2systems.schemas.account.ListHouseHoldsRequest request)*
     */
    public com.z2systems.schemas.account.ListHouseHoldsResponse listHouseHolds(com.z2systems.schemas.account.ListHouseHoldsRequest request) { 
        LOG.info("Executing operation listHouseHolds");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListHouseHoldsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listOrganizationContacts(com.z2systems.schemas.account.ListOrganizationContactsRequest request)*
     */
    public com.z2systems.schemas.account.ListOrganizationContactsResponse listOrganizationContacts(com.z2systems.schemas.account.ListOrganizationContactsRequest request) { 
        LOG.info("Executing operation listOrganizationContacts");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListOrganizationContactsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#updateIndividualAccount(com.z2systems.schemas.account.UpdateIndividualAccountRequest request)*
     */
    public com.z2systems.schemas.account.UpdateIndividualAccountResponse updateIndividualAccount(com.z2systems.schemas.account.UpdateIndividualAccountRequest request) { 
        LOG.info("Executing operation updateIndividualAccount");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.UpdateIndividualAccountResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#addActivity(com.z2systems.schemas.account.AddActivityRequest request)*
     */
    public com.z2systems.schemas.account.AddActivityResponse addActivity(com.z2systems.schemas.account.AddActivityRequest request) { 
        LOG.info("Executing operation addActivity");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.AddActivityResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#updateHouseHold(com.z2systems.schemas.account.UpdateHouseHoldRequest request)*
     */
    public com.z2systems.schemas.account.UpdateHouseHoldResponse updateHouseHold(com.z2systems.schemas.account.UpdateHouseHoldRequest request) { 
        LOG.info("Executing operation updateHouseHold");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.UpdateHouseHoldResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#removeIndividualFromOrganization(com.z2systems.schemas.account.RemoveIndividualFromOrganizationRequest request)*
     */
    public com.z2systems.schemas.account.RemoveIndividualFromOrganizationResponse removeIndividualFromOrganization(com.z2systems.schemas.account.RemoveIndividualFromOrganizationRequest request) { 
        LOG.info("Executing operation removeIndividualFromOrganization");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.RemoveIndividualFromOrganizationResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listAccountsByDefault(com.z2systems.schemas.account.ListAccountsByDefaultRequest request)*
     */
    public com.z2systems.schemas.account.ListAccountsByDefaultResponse listAccountsByDefault(com.z2systems.schemas.account.ListAccountsByDefaultRequest request) { 
        LOG.info("Executing operation listAccountsByDefault");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListAccountsByDefaultResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listAddressTypes(com.z2systems.schemas.account.ListAddressTypesRequest request)*
     */
    public com.z2systems.schemas.account.ListAddressTypesResponse listAddressTypes(com.z2systems.schemas.account.ListAddressTypesRequest request) { 
        LOG.info("Executing operation listAddressTypes");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListAddressTypesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listGenders(com.z2systems.schemas.account.ListGendersRequest request)*
     */
    public com.z2systems.schemas.account.ListGendersResponse listGenders(com.z2systems.schemas.account.ListGendersRequest request) { 
        LOG.info("Executing operation listGenders");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListGendersResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#deleteHouseHold(com.z2systems.schemas.account.DeleteHouseHoldRequest request)*
     */
    public com.z2systems.schemas.account.DeleteHouseHoldResponse deleteHouseHold(com.z2systems.schemas.account.DeleteHouseHoldRequest request) { 
        LOG.info("Executing operation deleteHouseHold");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.DeleteHouseHoldResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#retrieveTransactionStats(com.z2systems.schemas.account.RetrieveTransactionStatsRequest request)*
     */
    public com.z2systems.schemas.account.RetrieveTransactionStatsResponse retrieveTransactionStats(com.z2systems.schemas.account.RetrieveTransactionStatsRequest request) { 
        LOG.info("Executing operation retrieveTransactionStats");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.RetrieveTransactionStatsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listActivities(com.z2systems.schemas.account.ListActivitiesRequest request)*
     */
    public com.z2systems.schemas.account.ListActivitiesResponse listActivities(com.z2systems.schemas.account.ListActivitiesRequest request) { 
        LOG.info("Executing operation listActivities");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListActivitiesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#syncAccounts(com.z2systems.schemas.account.SyncAccountsRequest request)*
     */
    public com.z2systems.schemas.account.SyncAccountsResponse syncAccounts(com.z2systems.schemas.account.SyncAccountsRequest request) { 
        LOG.info("Executing operation syncAccounts");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.SyncAccountsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#updateOrganizationAccount(com.z2systems.schemas.account.UpdateOrganizationAccountRequest request)*
     */
    public com.z2systems.schemas.account.UpdateOrganizationAccountResponse updateOrganizationAccount(com.z2systems.schemas.account.UpdateOrganizationAccountRequest request) { 
        LOG.info("Executing operation updateOrganizationAccount");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.UpdateOrganizationAccountResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listOrganizationTypes(com.z2systems.schemas.account.ListOrganizationTypesRequest request)*
     */
    public com.z2systems.schemas.account.ListOrganizationTypesResponse listOrganizationTypes(com.z2systems.schemas.account.ListOrganizationTypesRequest request) { 
        LOG.info("Executing operation listOrganizationTypes");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListOrganizationTypesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#createHouseHold(com.z2systems.schemas.account.CreateHouseHoldRequest request)*
     */
    public com.z2systems.schemas.account.CreateHouseHoldResponse createHouseHold(com.z2systems.schemas.account.CreateHouseHoldRequest request) { 
        LOG.info("Executing operation createHouseHold");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.CreateHouseHoldResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#retrieveOrganizationAccount(com.z2systems.schemas.account.RetrieveOrganizationAccountRequest request)*
     */
    public com.z2systems.schemas.account.RetrieveOrganizationAccountResponse retrieveOrganizationAccount(com.z2systems.schemas.account.RetrieveOrganizationAccountRequest request) { 
        LOG.info("Executing operation retrieveOrganizationAccount");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.RetrieveOrganizationAccountResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listPrefixes(com.z2systems.schemas.account.ListPrefixesRequest request)*
     */
    public com.z2systems.schemas.account.ListPrefixesResponse listPrefixes(com.z2systems.schemas.account.ListPrefixesRequest request) { 
        LOG.info("Executing operation listPrefixes");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListPrefixesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listAccountsBySearchCriteria(com.z2systems.schemas.account.ListAccountsBySearchCriteriaRequest request)*
     */
    public com.z2systems.schemas.account.ListAccountsBySearchCriteriaResponse listAccountsBySearchCriteria(com.z2systems.schemas.account.ListAccountsBySearchCriteriaRequest request) { 
        LOG.info("Executing operation listAccountsBySearchCriteria");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListAccountsBySearchCriteriaResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listActivityStatus(com.z2systems.schemas.account.ListActivityStatusRequest request)*
     */
    public com.z2systems.schemas.account.ListActivityStatusResponse listActivityStatus(com.z2systems.schemas.account.ListActivityStatusRequest request) { 
        LOG.info("Executing operation listActivityStatus");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListActivityStatusResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listSystemUsers(com.z2systems.schemas.account.ListSystemUsersRequest request)*
     */
    public com.z2systems.schemas.account.ListSystemUsersResponse listSystemUsers(com.z2systems.schemas.account.ListSystemUsersRequest request) { 
        LOG.info("Executing operation listSystemUsers");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListSystemUsersResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listRelationTypes(com.z2systems.schemas.account.ListRelationTypesRequest request)*
     */
    public com.z2systems.schemas.account.ListRelationTypesResponse listRelationTypes(com.z2systems.schemas.account.ListRelationTypesRequest request) { 
        LOG.info("Executing operation listRelationTypes");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListRelationTypesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.AccountService#listAccounts(com.z2systems.schemas.account.ListAccountsRequest request)*
     */
    public com.z2systems.schemas.account.ListAccountsResponse listAccounts(com.z2systems.schemas.account.ListAccountsRequest request) { 
        LOG.info("Executing operation listAccounts");
        System.out.println(request);
        try {
            com.z2systems.schemas.account.ListAccountsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
