package com.z2systems.schemas.neonws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T17:30:59.691Z
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://www.z2systems.com/schemas/neonws/", name = "AccountService")
@XmlSeeAlso({com.z2systems.schemas.membership.ObjectFactory.class, com.z2systems.schemas.common.ObjectFactory.class, com.z2systems.schemas.account.ObjectFactory.class, com.z2systems.schemas.donation.ObjectFactory.class, com.z2systems.schemas.store.ObjectFactory.class, ObjectFactory.class, com.z2systems.schemas.event.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AccountService {

    @WebResult(name = "removeAddressResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.RemoveAddressResponse removeAddress(
            @WebParam(partName = "request", name = "removeAddressRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.RemoveAddressRequest request
    );

    @WebResult(name = "listSourcesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListSourcesResponse listSources(
            @WebParam(partName = "request", name = "listSourcesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListSourcesRequest request
    );

    @WebResult(name = "updateActivityResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.UpdateActivityResponse updateActivity(
            @WebParam(partName = "request", name = "updateActivityRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.UpdateActivityRequest request
    );

    @WebResult(name = "retrieveActivityResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.RetrieveActivityResponse retrieveActivity(
            @WebParam(partName = "request", name = "retrieveActivityRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.RetrieveActivityRequest request
    );

    @WebResult(name = "editIndividualAccountResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.EditIndividualAccountResponse editIndividualAccount(
            @WebParam(partName = "request", name = "editIndividualAccountRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.EditIndividualAccountRequest request
    );

    @WebResult(name = "addAddressResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.AddAddressResponse addAddress(
            @WebParam(partName = "request", name = "addAddressRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.AddAddressRequest request
    );

    @WebResult(name = "listIndividualTypesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListIndividualTypesResponse listIndividualTypes(
            @WebParam(partName = "request", name = "listIndividualTypesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListIndividualTypesRequest request
    );

    @WebResult(name = "AddToFavoriteAccountsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.AddToFavoriteAccountsResponse addToFavoriteAccounts(
            @WebParam(partName = "request", name = "AddToFavoirteAccountsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.AddToFavoirteAccountsRequest request
    );

    @WebResult(name = "editOrganizationAccountResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.EditOrganizationAccountResponse editOrganizationAccount(
            @WebParam(partName = "request", name = "editOrganizationAccountRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.EditOrganizationAccountRequest request
    );

    @WebResult(name = "listAccountsByKeywordSearchResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListAccountsByKeywordSearchResponse listAccountsByKeywordSearch(
            @WebParam(partName = "request", name = "listAccountsByKeywordSearchRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListAccountsByKeywordSearchRequest request
    );

    @WebResult(name = "removeActivityResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.RemoveActivityResponse removeActivity(
            @WebParam(partName = "request", name = "removeActivityRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.RemoveActivityRequest request
    );

    @WebResult(name = "createOrganizationAccountResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.CreateOrganizationAccountResponse createOrganizationAccount(
            @WebParam(partName = "request", name = "createOrganizationAccountRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.CreateOrganizationAccountRequest request
    );

    @WebResult(name = "updateHouseHoldPrimaryResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.UpdateHouseHoldPrimaryResponse updateHouseHoldPrimary(
            @WebParam(partName = "request", name = "updateHouseHoldPrimaryRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.UpdateHouseHoldPrimaryRequest request
    );

    @WebResult(name = "addIndividualToHouseHoldResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.AddIndividualToHouseHoldResponse addIndividualToHouseHold(
            @WebParam(partName = "request", name = "addIndividualToHouseHoldRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.AddIndividualToHouseHoldRequest request
    );

    @WebResult(name = "updateAddressResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.UpdateAddressResponse updateAddress(
            @WebParam(partName = "request", name = "updateAddressRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.UpdateAddressRequest request
    );

    @WebResult(name = "removeIndividualFromHouseHoldResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.RemoveIndividualFromHouseHoldResponse removeIndividualFromHouseHold(
            @WebParam(partName = "request", name = "removeIndividualFromHouseHoldRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.RemoveIndividualFromHouseHoldRequest request
    );

    @WebResult(name = "linkIndividualToOrganizationResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.LinkIndividualToOrganizationResponse linkIndividualToOrganization(
            @WebParam(partName = "request", name = "linkIndividualToOrganizationRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.LinkIndividualToOrganizationRequest request
    );

    @WebResult(name = "listCountriesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListCountriesResponse listCountries(
            @WebParam(partName = "request", name = "listCountriesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListCountriesRequest request
    );

    @WebResult(name = "ListFavoriteAccountsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListFavoriteAccountsResponse listFavoriteAccounts(
            @WebParam(partName = "request", name = "ListFavoriteAccountsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListFavoriteAccountsRequest request
    );

    @WebResult(name = "RemoveFromFavoriteAccountsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.RemoveFromFavoriteAccountsResponse removeFromFavoriteAccounts(
            @WebParam(partName = "request", name = "RemoveFromFavoriteAccountsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.RemoveFromFavoriteAccountsRequest request
    );

    @WebResult(name = "retrieveIndividualAccountResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.RetrieveIndividualAccountResponse retrieveIndividualAccount(
            @WebParam(partName = "request", name = "retrieveIndividualAccountRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.RetrieveIndividualAccountRequest request
    );

    @WebResult(name = "syncActivitiesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.SyncActivitiesResponse syncActivities(
            @WebParam(partName = "request", name = "syncActivitiesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.SyncActivitiesRequest request
    );

    @WebResult(name = "listStatesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListStatesResponse listStates(
            @WebParam(partName = "request", name = "listStatesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListStatesRequest request
    );

    @WebResult(name = "createIndividualAccountResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.CreateIndividualAccountResponse createIndividualAccount(
            @WebParam(partName = "request", name = "createIndividualAccountRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.CreateIndividualAccountRequest request
    );

    @WebResult(name = "listHouseHoldsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListHouseHoldsResponse listHouseHolds(
            @WebParam(partName = "request", name = "listHouseHoldsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListHouseHoldsRequest request
    );

    @WebResult(name = "listOrganizationContactsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListOrganizationContactsResponse listOrganizationContacts(
            @WebParam(partName = "request", name = "listOrganizationContactsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListOrganizationContactsRequest request
    );

    @WebResult(name = "updateIndividualAccountResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.UpdateIndividualAccountResponse updateIndividualAccount(
            @WebParam(partName = "request", name = "updateIndividualAccountRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.UpdateIndividualAccountRequest request
    );

    @WebResult(name = "addActivityResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.AddActivityResponse addActivity(
            @WebParam(partName = "request", name = "addActivityRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.AddActivityRequest request
    );

    @WebResult(name = "updateHouseHoldResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.UpdateHouseHoldResponse updateHouseHold(
            @WebParam(partName = "request", name = "updateHouseHoldRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.UpdateHouseHoldRequest request
    );

    @WebResult(name = "removeIndividualFromOrganizationResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.RemoveIndividualFromOrganizationResponse removeIndividualFromOrganization(
            @WebParam(partName = "request", name = "removeIndividualFromOrganizationRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.RemoveIndividualFromOrganizationRequest request
    );

    @WebResult(name = "listAccountsByDefaultResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListAccountsByDefaultResponse listAccountsByDefault(
            @WebParam(partName = "request", name = "listAccountsByDefaultRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListAccountsByDefaultRequest request
    );

    @WebResult(name = "listAddressTypesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListAddressTypesResponse listAddressTypes(
            @WebParam(partName = "request", name = "listAddressTypesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListAddressTypesRequest request
    );

    @WebResult(name = "listGendersResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListGendersResponse listGenders(
            @WebParam(partName = "request", name = "listGendersRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListGendersRequest request
    );

    @WebResult(name = "deleteHouseHoldResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.DeleteHouseHoldResponse deleteHouseHold(
            @WebParam(partName = "request", name = "deleteHouseHoldRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.DeleteHouseHoldRequest request
    );

    @WebResult(name = "retrieveTransactionStatsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.RetrieveTransactionStatsResponse retrieveTransactionStats(
            @WebParam(partName = "request", name = "retrieveTransactionStatsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.RetrieveTransactionStatsRequest request
    );

    @WebResult(name = "listActivitiesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListActivitiesResponse listActivities(
            @WebParam(partName = "request", name = "listActivitiesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListActivitiesRequest request
    );

    @WebResult(name = "syncAccountsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.SyncAccountsResponse syncAccounts(
            @WebParam(partName = "request", name = "syncAccountsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.SyncAccountsRequest request
    );

    @WebResult(name = "updateOrganizationAccountResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.UpdateOrganizationAccountResponse updateOrganizationAccount(
            @WebParam(partName = "request", name = "updateOrganizationAccountRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.UpdateOrganizationAccountRequest request
    );

    @WebResult(name = "listOrganizationTypesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListOrganizationTypesResponse listOrganizationTypes(
            @WebParam(partName = "request", name = "listOrganizationTypesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListOrganizationTypesRequest request
    );

    @WebResult(name = "createHouseHoldResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.CreateHouseHoldResponse createHouseHold(
            @WebParam(partName = "request", name = "createHouseHoldRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.CreateHouseHoldRequest request
    );

    @WebResult(name = "retrieveOrganizationAccountResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.RetrieveOrganizationAccountResponse retrieveOrganizationAccount(
            @WebParam(partName = "request", name = "retrieveOrganizationAccountRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.RetrieveOrganizationAccountRequest request
    );

    @WebResult(name = "listPrefixesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListPrefixesResponse listPrefixes(
            @WebParam(partName = "request", name = "listPrefixesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListPrefixesRequest request
    );

    @WebResult(name = "listAccountsBySearchCriteriaResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListAccountsBySearchCriteriaResponse listAccountsBySearchCriteria(
            @WebParam(partName = "request", name = "listAccountsBySearchCriteriaRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListAccountsBySearchCriteriaRequest request
    );

    @WebResult(name = "listActivityStatusResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListActivityStatusResponse listActivityStatus(
            @WebParam(partName = "request", name = "listActivityStatusRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListActivityStatusRequest request
    );

    @WebResult(name = "listSystemUsersResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListSystemUsersResponse listSystemUsers(
            @WebParam(partName = "request", name = "listSystemUsersRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListSystemUsersRequest request
    );

    @WebResult(name = "listRelationTypesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListRelationTypesResponse listRelationTypes(
            @WebParam(partName = "request", name = "listRelationTypesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListRelationTypesRequest request
    );

    @WebResult(name = "listAccountsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.account.ListAccountsResponse listAccounts(
            @WebParam(partName = "request", name = "listAccountsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.account.ListAccountsRequest request
    );
}
