package com.z2systems.schemas.neonws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T17:30:59.773Z
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://www.z2systems.com/schemas/neonws/", name = "CommonService")
@XmlSeeAlso({com.z2systems.schemas.membership.ObjectFactory.class, com.z2systems.schemas.common.ObjectFactory.class, com.z2systems.schemas.account.ObjectFactory.class, com.z2systems.schemas.donation.ObjectFactory.class, com.z2systems.schemas.store.ObjectFactory.class, ObjectFactory.class, com.z2systems.schemas.event.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CommonService {

    @WebResult(name = "logoutResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.common.LogoutResponse logout(
            @WebParam(partName = "request", name = "logoutRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.common.LogoutRequest request
    );

    @WebResult(name = "loginResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.common.LoginResponse login(
            @WebParam(partName = "request", name = "loginRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.common.LoginRequest request
    );

    @WebResult(name = "updatePaymentResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.common.UpdatePaymentResponse updatePayment(
            @WebParam(partName = "request", name = "updatePaymentRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.common.UpdatePaymentRequest request
    );

    @WebResult(name = "authenticateUserResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.common.AuthenticateUserResponse authenticateUser(
            @WebParam(partName = "request", name = "authenticateUserRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.common.AuthenticateUserRequest request
    );

    @WebResult(name = "retrieveStatsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.common.RetrieveStatsResponse retrieveStats(
            @WebParam(partName = "request", name = "retrieveStatsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.common.RetrieveStatsRequest request
    );

    @WebResult(name = "retrieveCurrentSystemUserResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.common.RetrieveCurrentSystemUserResponse retrieveCurrentSystemUser(
            @WebParam(partName = "request", name = "retrieveCurrentSystemUserRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.common.RetrieveCurrentSystemUserRequest request
    );

    @WebResult(name = "listCreditCardTypesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.common.ListCreditCardTypesResponse listCreditCardTypes(
            @WebParam(partName = "request", name = "listCreditCardTypesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.common.ListCreditCardTypesRequest request
    );

    @WebResult(name = "listTendersResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.common.ListTendersResponse listTenders(
            @WebParam(partName = "request", name = "listTendersRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.common.ListTendersRequest request
    );

    @WebResult(name = "listCustomFieldsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.common.ListCustomFieldsResponse listCustomFields(
            @WebParam(partName = "request", name = "listCustomFieldsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.common.ListCustomFieldsRequest request
    );
}
