package com.z2systems.schemas.neonws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T17:30:59.669Z
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://www.z2systems.com/schemas/neonws/", name = "DonationService")
@XmlSeeAlso({com.z2systems.schemas.membership.ObjectFactory.class, com.z2systems.schemas.common.ObjectFactory.class, com.z2systems.schemas.account.ObjectFactory.class, com.z2systems.schemas.donation.ObjectFactory.class, com.z2systems.schemas.store.ObjectFactory.class, ObjectFactory.class, com.z2systems.schemas.event.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DonationService {

    @WebResult(name = "listRecurringDonorsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.donation.ListRecurringDonorsResponse listRecurringDonors(
            @WebParam(partName = "request", name = "listRecurringDonorsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.donation.ListRecurringDonorsRequest request
    );

    @WebResult(name = "listCampaignsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.donation.ListCampaignsResponse listCampaigns(
            @WebParam(partName = "request", name = "listCampaignsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.donation.ListCampaignsRequest request
    );

    @WebResult(name = "listPurposesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.donation.ListPurposesResponse listPurposes(
            @WebParam(partName = "request", name = "listPurposesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.donation.ListPurposesRequest request
    );

    @WebResult(name = "listSolicitationMethodsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.donation.ListSolicitationMethodsResponse listSolicitationMethods(
            @WebParam(partName = "request", name = "listSolicitationMethodsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.donation.ListSolicitationMethodsRequest request
    );

    @WebResult(name = "retrieveCampaignSummaryResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.donation.RetrieveCampaignSummaryResponse retrieveCampaignSummary(
            @WebParam(partName = "request", name = "retrieveCampaignSummaryRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.donation.RetrieveCampaignSummaryRequest request
    );

    @WebResult(name = "createRecurringDonationResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.donation.CreateRecurringDonationResponse createRecurringDonation(
            @WebParam(partName = "request", name = "createRecurringDonationRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.donation.CreateRecurringDonationRequest request
    );

    @WebResult(name = "createDonationResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.donation.CreateDonationResponse createDonation(
            @WebParam(partName = "request", name = "createDonationRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.donation.CreateDonationRequest request
    );

    @WebResult(name = "retrieveDonationStatsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.donation.RetrieveDonationStatsResponse retrieveDonationStats(
            @WebParam(partName = "request", name = "retrieveDonationStatsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.donation.RetrieveDonationStatsRequest request
    );

    @WebResult(name = "listFundsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.donation.ListFundsResponse listFunds(
            @WebParam(partName = "request", name = "listFundsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.donation.ListFundsRequest request
    );

    @WebResult(name = "createPledgePaymentResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.donation.CreatePledgePaymentResponse createPledgePayment(
            @WebParam(partName = "request", name = "createPledgePaymentRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.donation.CreatePledgePaymentRequest request
    );

    @WebResult(name = "createPledgeResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.donation.CreatePledgeResponse createPledge(
            @WebParam(partName = "request", name = "createPledgeRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.donation.CreatePledgeRequest request
    );

    @WebResult(name = "listDonationsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.donation.ListDonationsResponse listDonations(
            @WebParam(partName = "request", name = "listDonationsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.donation.ListDonationsRequest request
    );
}
