
package com.z2systems.schemas.neonws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T17:30:59.288Z
 * Generated source version: 3.1.11
 * 
 */
public final class DonationService_DonationPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.z2systems.com/schemas/neonws/", "Neonws");

    private DonationService_DonationPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Neonws.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Neonws ss = new Neonws(wsdlURL, SERVICE_NAME);
        DonationService port = ss.getDonationPort();  
        
        {
        System.out.println("Invoking listRecurringDonors...");
        com.z2systems.schemas.donation.ListRecurringDonorsRequest _listRecurringDonors_request = null;
        com.z2systems.schemas.donation.ListRecurringDonorsResponse _listRecurringDonors__return = port.listRecurringDonors(_listRecurringDonors_request);
        System.out.println("listRecurringDonors.result=" + _listRecurringDonors__return);


        }
        {
        System.out.println("Invoking listCampaigns...");
        com.z2systems.schemas.donation.ListCampaignsRequest _listCampaigns_request = null;
        com.z2systems.schemas.donation.ListCampaignsResponse _listCampaigns__return = port.listCampaigns(_listCampaigns_request);
        System.out.println("listCampaigns.result=" + _listCampaigns__return);


        }
        {
        System.out.println("Invoking listPurposes...");
        com.z2systems.schemas.donation.ListPurposesRequest _listPurposes_request = null;
        com.z2systems.schemas.donation.ListPurposesResponse _listPurposes__return = port.listPurposes(_listPurposes_request);
        System.out.println("listPurposes.result=" + _listPurposes__return);


        }
        {
        System.out.println("Invoking listSolicitationMethods...");
        com.z2systems.schemas.donation.ListSolicitationMethodsRequest _listSolicitationMethods_request = null;
        com.z2systems.schemas.donation.ListSolicitationMethodsResponse _listSolicitationMethods__return = port.listSolicitationMethods(_listSolicitationMethods_request);
        System.out.println("listSolicitationMethods.result=" + _listSolicitationMethods__return);


        }
        {
        System.out.println("Invoking retrieveCampaignSummary...");
        com.z2systems.schemas.donation.RetrieveCampaignSummaryRequest _retrieveCampaignSummary_request = null;
        com.z2systems.schemas.donation.RetrieveCampaignSummaryResponse _retrieveCampaignSummary__return = port.retrieveCampaignSummary(_retrieveCampaignSummary_request);
        System.out.println("retrieveCampaignSummary.result=" + _retrieveCampaignSummary__return);


        }
        {
        System.out.println("Invoking createRecurringDonation...");
        com.z2systems.schemas.donation.CreateRecurringDonationRequest _createRecurringDonation_request = null;
        com.z2systems.schemas.donation.CreateRecurringDonationResponse _createRecurringDonation__return = port.createRecurringDonation(_createRecurringDonation_request);
        System.out.println("createRecurringDonation.result=" + _createRecurringDonation__return);


        }
        {
        System.out.println("Invoking createDonation...");
        com.z2systems.schemas.donation.CreateDonationRequest _createDonation_request = null;
        com.z2systems.schemas.donation.CreateDonationResponse _createDonation__return = port.createDonation(_createDonation_request);
        System.out.println("createDonation.result=" + _createDonation__return);


        }
        {
        System.out.println("Invoking retrieveDonationStats...");
        com.z2systems.schemas.donation.RetrieveDonationStatsRequest _retrieveDonationStats_request = null;
        com.z2systems.schemas.donation.RetrieveDonationStatsResponse _retrieveDonationStats__return = port.retrieveDonationStats(_retrieveDonationStats_request);
        System.out.println("retrieveDonationStats.result=" + _retrieveDonationStats__return);


        }
        {
        System.out.println("Invoking listFunds...");
        com.z2systems.schemas.donation.ListFundsRequest _listFunds_request = null;
        com.z2systems.schemas.donation.ListFundsResponse _listFunds__return = port.listFunds(_listFunds_request);
        System.out.println("listFunds.result=" + _listFunds__return);


        }
        {
        System.out.println("Invoking createPledgePayment...");
        com.z2systems.schemas.donation.CreatePledgePaymentRequest _createPledgePayment_request = null;
        com.z2systems.schemas.donation.CreatePledgePaymentResponse _createPledgePayment__return = port.createPledgePayment(_createPledgePayment_request);
        System.out.println("createPledgePayment.result=" + _createPledgePayment__return);


        }
        {
        System.out.println("Invoking createPledge...");
        com.z2systems.schemas.donation.CreatePledgeRequest _createPledge_request = null;
        com.z2systems.schemas.donation.CreatePledgeResponse _createPledge__return = port.createPledge(_createPledge_request);
        System.out.println("createPledge.result=" + _createPledge__return);


        }
        {
        System.out.println("Invoking listDonations...");
        com.z2systems.schemas.donation.ListDonationsRequest _listDonations_request = null;
        com.z2systems.schemas.donation.ListDonationsResponse _listDonations__return = port.listDonations(_listDonations_request);
        System.out.println("listDonations.result=" + _listDonations__return);


        }

        System.exit(0);
    }

}
