
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.z2systems.schemas.neonws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T17:30:59.507Z
 * Generated source version: 3.1.11
 * 
 */

@WebService(
                      serviceName = "Neonws",
                      portName = "DonationPort",
                      targetNamespace = "http://www.z2systems.com/schemas/neonws/",
                      wsdlLocation = "file:../wsdl/definitions.wsdl",
                      endpointInterface = "com.z2systems.schemas.neonws.DonationService")
                      
public class DonationPortImpl implements DonationService {

    private static final Logger LOG = Logger.getLogger(DonationPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.DonationService#listRecurringDonors(com.z2systems.schemas.donation.ListRecurringDonorsRequest request)*
     */
    public com.z2systems.schemas.donation.ListRecurringDonorsResponse listRecurringDonors(com.z2systems.schemas.donation.ListRecurringDonorsRequest request) { 
        LOG.info("Executing operation listRecurringDonors");
        System.out.println(request);
        try {
            com.z2systems.schemas.donation.ListRecurringDonorsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.DonationService#listCampaigns(com.z2systems.schemas.donation.ListCampaignsRequest request)*
     */
    public com.z2systems.schemas.donation.ListCampaignsResponse listCampaigns(com.z2systems.schemas.donation.ListCampaignsRequest request) { 
        LOG.info("Executing operation listCampaigns");
        System.out.println(request);
        try {
            com.z2systems.schemas.donation.ListCampaignsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.DonationService#listPurposes(com.z2systems.schemas.donation.ListPurposesRequest request)*
     */
    public com.z2systems.schemas.donation.ListPurposesResponse listPurposes(com.z2systems.schemas.donation.ListPurposesRequest request) { 
        LOG.info("Executing operation listPurposes");
        System.out.println(request);
        try {
            com.z2systems.schemas.donation.ListPurposesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.DonationService#listSolicitationMethods(com.z2systems.schemas.donation.ListSolicitationMethodsRequest request)*
     */
    public com.z2systems.schemas.donation.ListSolicitationMethodsResponse listSolicitationMethods(com.z2systems.schemas.donation.ListSolicitationMethodsRequest request) { 
        LOG.info("Executing operation listSolicitationMethods");
        System.out.println(request);
        try {
            com.z2systems.schemas.donation.ListSolicitationMethodsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.DonationService#retrieveCampaignSummary(com.z2systems.schemas.donation.RetrieveCampaignSummaryRequest request)*
     */
    public com.z2systems.schemas.donation.RetrieveCampaignSummaryResponse retrieveCampaignSummary(com.z2systems.schemas.donation.RetrieveCampaignSummaryRequest request) { 
        LOG.info("Executing operation retrieveCampaignSummary");
        System.out.println(request);
        try {
            com.z2systems.schemas.donation.RetrieveCampaignSummaryResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.DonationService#createRecurringDonation(com.z2systems.schemas.donation.CreateRecurringDonationRequest request)*
     */
    public com.z2systems.schemas.donation.CreateRecurringDonationResponse createRecurringDonation(com.z2systems.schemas.donation.CreateRecurringDonationRequest request) { 
        LOG.info("Executing operation createRecurringDonation");
        System.out.println(request);
        try {
            com.z2systems.schemas.donation.CreateRecurringDonationResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.DonationService#createDonation(com.z2systems.schemas.donation.CreateDonationRequest request)*
     */
    public com.z2systems.schemas.donation.CreateDonationResponse createDonation(com.z2systems.schemas.donation.CreateDonationRequest request) { 
        LOG.info("Executing operation createDonation");
        System.out.println(request);
        try {
            com.z2systems.schemas.donation.CreateDonationResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.DonationService#retrieveDonationStats(com.z2systems.schemas.donation.RetrieveDonationStatsRequest request)*
     */
    public com.z2systems.schemas.donation.RetrieveDonationStatsResponse retrieveDonationStats(com.z2systems.schemas.donation.RetrieveDonationStatsRequest request) { 
        LOG.info("Executing operation retrieveDonationStats");
        System.out.println(request);
        try {
            com.z2systems.schemas.donation.RetrieveDonationStatsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.DonationService#listFunds(com.z2systems.schemas.donation.ListFundsRequest request)*
     */
    public com.z2systems.schemas.donation.ListFundsResponse listFunds(com.z2systems.schemas.donation.ListFundsRequest request) { 
        LOG.info("Executing operation listFunds");
        System.out.println(request);
        try {
            com.z2systems.schemas.donation.ListFundsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.DonationService#createPledgePayment(com.z2systems.schemas.donation.CreatePledgePaymentRequest request)*
     */
    public com.z2systems.schemas.donation.CreatePledgePaymentResponse createPledgePayment(com.z2systems.schemas.donation.CreatePledgePaymentRequest request) { 
        LOG.info("Executing operation createPledgePayment");
        System.out.println(request);
        try {
            com.z2systems.schemas.donation.CreatePledgePaymentResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.DonationService#createPledge(com.z2systems.schemas.donation.CreatePledgeRequest request)*
     */
    public com.z2systems.schemas.donation.CreatePledgeResponse createPledge(com.z2systems.schemas.donation.CreatePledgeRequest request) { 
        LOG.info("Executing operation createPledge");
        System.out.println(request);
        try {
            com.z2systems.schemas.donation.CreatePledgeResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.DonationService#listDonations(com.z2systems.schemas.donation.ListDonationsRequest request)*
     */
    public com.z2systems.schemas.donation.ListDonationsResponse listDonations(com.z2systems.schemas.donation.ListDonationsRequest request) { 
        LOG.info("Executing operation listDonations");
        System.out.println(request);
        try {
            com.z2systems.schemas.donation.ListDonationsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
