package com.z2systems.schemas.neonws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T17:30:59.708Z
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://www.z2systems.com/schemas/neonws/", name = "EventService")
@XmlSeeAlso({com.z2systems.schemas.membership.ObjectFactory.class, com.z2systems.schemas.common.ObjectFactory.class, com.z2systems.schemas.account.ObjectFactory.class, com.z2systems.schemas.donation.ObjectFactory.class, com.z2systems.schemas.store.ObjectFactory.class, ObjectFactory.class, com.z2systems.schemas.event.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EventService {

    @WebResult(name = "listEventsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.event.ListEventsResponse listEvents(
            @WebParam(partName = "request", name = "listEventsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.event.ListEventsRequest request
    );

    @WebResult(name = "retrieveEventAttendeesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.event.RetrieveEventAttendeesResponse retrieveEventAttendees(
            @WebParam(partName = "request", name = "retrieveEventAttendeesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.event.RetrieveEventAttendeesRequest request
    );

    @WebResult(name = "retrieveEventRegistrationStatsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.event.RetrieveEventRegistrationStatsResponse retrieveEventRegistrationStats(
            @WebParam(partName = "request", name = "retrieveEventRegistrationStatsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.event.RetrieveEventRegistrationStatsRequest request
    );
}
