
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.z2systems.schemas.neonws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T17:30:59.594Z
 * Generated source version: 3.1.11
 * 
 */

@WebService(
                      serviceName = "Neonws",
                      portName = "EventPort",
                      targetNamespace = "http://www.z2systems.com/schemas/neonws/",
                      wsdlLocation = "file:../wsdl/definitions.wsdl",
                      endpointInterface = "com.z2systems.schemas.neonws.EventService")
                      
public class EventPortImpl implements EventService {

    private static final Logger LOG = Logger.getLogger(EventPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.EventService#listEvents(com.z2systems.schemas.event.ListEventsRequest request)*
     */
    public com.z2systems.schemas.event.ListEventsResponse listEvents(com.z2systems.schemas.event.ListEventsRequest request) { 
        LOG.info("Executing operation listEvents");
        System.out.println(request);
        try {
            com.z2systems.schemas.event.ListEventsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.EventService#retrieveEventAttendees(com.z2systems.schemas.event.RetrieveEventAttendeesRequest request)*
     */
    public com.z2systems.schemas.event.RetrieveEventAttendeesResponse retrieveEventAttendees(com.z2systems.schemas.event.RetrieveEventAttendeesRequest request) { 
        LOG.info("Executing operation retrieveEventAttendees");
        System.out.println(request);
        try {
            com.z2systems.schemas.event.RetrieveEventAttendeesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.EventService#retrieveEventRegistrationStats(com.z2systems.schemas.event.RetrieveEventRegistrationStatsRequest request)*
     */
    public com.z2systems.schemas.event.RetrieveEventRegistrationStatsResponse retrieveEventRegistrationStats(com.z2systems.schemas.event.RetrieveEventRegistrationStatsRequest request) { 
        LOG.info("Executing operation retrieveEventRegistrationStats");
        System.out.println(request);
        try {
            com.z2systems.schemas.event.RetrieveEventRegistrationStatsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
