
package com.z2systems.schemas.neonws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T17:30:59.431Z
 * Generated source version: 3.1.11
 * 
 */
public final class EventService_EventPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.z2systems.com/schemas/neonws/", "Neonws");

    private EventService_EventPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Neonws.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Neonws ss = new Neonws(wsdlURL, SERVICE_NAME);
        EventService port = ss.getEventPort();  
        
        {
        System.out.println("Invoking listEvents...");
        com.z2systems.schemas.event.ListEventsRequest _listEvents_request = null;
        com.z2systems.schemas.event.ListEventsResponse _listEvents__return = port.listEvents(_listEvents_request);
        System.out.println("listEvents.result=" + _listEvents__return);


        }
        {
        System.out.println("Invoking retrieveEventAttendees...");
        com.z2systems.schemas.event.RetrieveEventAttendeesRequest _retrieveEventAttendees_request = null;
        com.z2systems.schemas.event.RetrieveEventAttendeesResponse _retrieveEventAttendees__return = port.retrieveEventAttendees(_retrieveEventAttendees_request);
        System.out.println("retrieveEventAttendees.result=" + _retrieveEventAttendees__return);


        }
        {
        System.out.println("Invoking retrieveEventRegistrationStats...");
        com.z2systems.schemas.event.RetrieveEventRegistrationStatsRequest _retrieveEventRegistrationStats_request = null;
        com.z2systems.schemas.event.RetrieveEventRegistrationStatsResponse _retrieveEventRegistrationStats__return = port.retrieveEventRegistrationStats(_retrieveEventRegistrationStats_request);
        System.out.println("retrieveEventRegistrationStats.result=" + _retrieveEventRegistrationStats__return);


        }

        System.exit(0);
    }

}
