package com.z2systems.schemas.neonws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T17:30:59.681Z
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://www.z2systems.com/schemas/neonws/", name = "MembershipService")
@XmlSeeAlso({com.z2systems.schemas.membership.ObjectFactory.class, com.z2systems.schemas.common.ObjectFactory.class, com.z2systems.schemas.account.ObjectFactory.class, com.z2systems.schemas.donation.ObjectFactory.class, com.z2systems.schemas.store.ObjectFactory.class, ObjectFactory.class, com.z2systems.schemas.event.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MembershipService {

    @WebResult(name = "listMembershipsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.membership.ListMembershipsResponse listMemberships(
            @WebParam(partName = "request", name = "listMembershipsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.membership.ListMembershipsRequest request
    );

    @WebResult(name = "retrieveMembershipStatsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.membership.RetrieveMembershipStatsResponse retrieveMembershipStats(
            @WebParam(partName = "request", name = "retrieveMembershipStatsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.membership.RetrieveMembershipStatsRequest request
    );

    @WebResult(name = "listMembershipHistoryResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.membership.ListMembershipHistoryResponse listMembershipHistory(
            @WebParam(partName = "request", name = "listMembershipHistoryRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.membership.ListMembershipHistoryRequest request
    );

    @WebResult(name = "listMembershipTermsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.membership.ListMembershipTermsResponse listMembershipTerms(
            @WebParam(partName = "request", name = "listMembershipTermsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.membership.ListMembershipTermsRequest request
    );

    @WebResult(name = "addMembershipToAccountResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.membership.AddMembershipToAccountResponse addMembershipToAccount(
            @WebParam(partName = "request", name = "addMembershipToAccountRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.membership.AddMembershipToAccountRequest request
    );
}
