
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.z2systems.schemas.neonws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T17:30:59.530Z
 * Generated source version: 3.1.11
 * 
 */

@WebService(
                      serviceName = "Neonws",
                      portName = "MembershipPort",
                      targetNamespace = "http://www.z2systems.com/schemas/neonws/",
                      wsdlLocation = "file:../wsdl/definitions.wsdl",
                      endpointInterface = "com.z2systems.schemas.neonws.MembershipService")
                      
public class MembershipPortImpl implements MembershipService {

    private static final Logger LOG = Logger.getLogger(MembershipPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.MembershipService#listMemberships(com.z2systems.schemas.membership.ListMembershipsRequest request)*
     */
    public com.z2systems.schemas.membership.ListMembershipsResponse listMemberships(com.z2systems.schemas.membership.ListMembershipsRequest request) { 
        LOG.info("Executing operation listMemberships");
        System.out.println(request);
        try {
            com.z2systems.schemas.membership.ListMembershipsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.MembershipService#retrieveMembershipStats(com.z2systems.schemas.membership.RetrieveMembershipStatsRequest request)*
     */
    public com.z2systems.schemas.membership.RetrieveMembershipStatsResponse retrieveMembershipStats(com.z2systems.schemas.membership.RetrieveMembershipStatsRequest request) { 
        LOG.info("Executing operation retrieveMembershipStats");
        System.out.println(request);
        try {
            com.z2systems.schemas.membership.RetrieveMembershipStatsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.MembershipService#listMembershipHistory(com.z2systems.schemas.membership.ListMembershipHistoryRequest request)*
     */
    public com.z2systems.schemas.membership.ListMembershipHistoryResponse listMembershipHistory(com.z2systems.schemas.membership.ListMembershipHistoryRequest request) { 
        LOG.info("Executing operation listMembershipHistory");
        System.out.println(request);
        try {
            com.z2systems.schemas.membership.ListMembershipHistoryResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.MembershipService#listMembershipTerms(com.z2systems.schemas.membership.ListMembershipTermsRequest request)*
     */
    public com.z2systems.schemas.membership.ListMembershipTermsResponse listMembershipTerms(com.z2systems.schemas.membership.ListMembershipTermsRequest request) { 
        LOG.info("Executing operation listMembershipTerms");
        System.out.println(request);
        try {
            com.z2systems.schemas.membership.ListMembershipTermsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.MembershipService#addMembershipToAccount(com.z2systems.schemas.membership.AddMembershipToAccountRequest request)*
     */
    public com.z2systems.schemas.membership.AddMembershipToAccountResponse addMembershipToAccount(com.z2systems.schemas.membership.AddMembershipToAccountRequest request) { 
        LOG.info("Executing operation addMembershipToAccount");
        System.out.println(request);
        try {
            com.z2systems.schemas.membership.AddMembershipToAccountResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
