
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.z2systems.schemas.neonws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T17:30:59.610Z
 * Generated source version: 3.1.11
 * 
 */

@WebService(
                      serviceName = "Neonws",
                      portName = "StorePort",
                      targetNamespace = "http://www.z2systems.com/schemas/neonws/",
                      wsdlLocation = "file:../wsdl/definitions.wsdl",
                      endpointInterface = "com.z2systems.schemas.neonws.StoreService")
                      
public class StorePortImpl implements StoreService {

    private static final Logger LOG = Logger.getLogger(StorePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#listOrders(com.z2systems.schemas.store.ListOrdersRequest request)*
     */
    public com.z2systems.schemas.store.ListOrdersResponse listOrders(com.z2systems.schemas.store.ListOrdersRequest request) { 
        LOG.info("Executing operation listOrders");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.ListOrdersResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#removeItemFromShoppingCart(com.z2systems.schemas.store.RemoveItemFromShoppingCartRequest request)*
     */
    public com.z2systems.schemas.store.RemoveItemFromShoppingCartResponse removeItemFromShoppingCart(com.z2systems.schemas.store.RemoveItemFromShoppingCartRequest request) { 
        LOG.info("Executing operation removeItemFromShoppingCart");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.RemoveItemFromShoppingCartResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#listProductOptions(com.z2systems.schemas.store.ListProductOptionsRequest request)*
     */
    public com.z2systems.schemas.store.ListProductOptionsResponse listProductOptions(com.z2systems.schemas.store.ListProductOptionsRequest request) { 
        LOG.info("Executing operation listProductOptions");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.ListProductOptionsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#removeCategory(com.z2systems.schemas.store.RemoveCategoryRequest request)*
     */
    public com.z2systems.schemas.store.RemoveCategoryResponse removeCategory(com.z2systems.schemas.store.RemoveCategoryRequest request) { 
        LOG.info("Executing operation removeCategory");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.RemoveCategoryResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#listCatalogs(com.z2systems.schemas.store.ListCatalogsRequest request)*
     */
    public com.z2systems.schemas.store.ListCatalogsResponse listCatalogs(com.z2systems.schemas.store.ListCatalogsRequest request) { 
        LOG.info("Executing operation listCatalogs");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.ListCatalogsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#listProductImages(com.z2systems.schemas.store.ListProductImagesRequest request)*
     */
    public com.z2systems.schemas.store.ListProductImagesResponse listProductImages(com.z2systems.schemas.store.ListProductImagesRequest request) { 
        LOG.info("Executing operation listProductImages");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.ListProductImagesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#addOrUpdateShippingAddressToShoppingCart(com.z2systems.schemas.store.AddOrUpdateShippingAddressToShoppingCartRequest request)*
     */
    public com.z2systems.schemas.store.AddOrUpdateShippingAddressToShoppingCartResponse addOrUpdateShippingAddressToShoppingCart(com.z2systems.schemas.store.AddOrUpdateShippingAddressToShoppingCartRequest request) { 
        LOG.info("Executing operation addOrUpdateShippingAddressToShoppingCart");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.AddOrUpdateShippingAddressToShoppingCartResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#listProducts(com.z2systems.schemas.store.ListProductsRequest request)*
     */
    public com.z2systems.schemas.store.ListProductsResponse listProducts(com.z2systems.schemas.store.ListProductsRequest request) { 
        LOG.info("Executing operation listProducts");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.ListProductsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#retrieveShoppingCartSummary(com.z2systems.schemas.store.RetrieveShoppingCartSummaryRequest request)*
     */
    public com.z2systems.schemas.store.RetrieveShoppingCartSummaryResponse retrieveShoppingCartSummary(com.z2systems.schemas.store.RetrieveShoppingCartSummaryRequest request) { 
        LOG.info("Executing operation retrieveShoppingCartSummary");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.RetrieveShoppingCartSummaryResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#retrieveReceipt(com.z2systems.schemas.store.RetrieveReceiptRequest request)*
     */
    public com.z2systems.schemas.store.RetrieveReceiptResponse retrieveReceipt(com.z2systems.schemas.store.RetrieveReceiptRequest request) { 
        LOG.info("Executing operation retrieveReceipt");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.RetrieveReceiptResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#checkout(com.z2systems.schemas.store.CheckoutRequest request)*
     */
    public com.z2systems.schemas.store.CheckoutResponse checkout(com.z2systems.schemas.store.CheckoutRequest request) { 
        LOG.info("Executing operation checkout");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.CheckoutResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#addItemToShoppingCart(com.z2systems.schemas.store.AddItemToShoppingCartRequest request)*
     */
    public com.z2systems.schemas.store.AddItemToShoppingCartResponse addItemToShoppingCart(com.z2systems.schemas.store.AddItemToShoppingCartRequest request) { 
        LOG.info("Executing operation addItemToShoppingCart");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.AddItemToShoppingCartResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#retrieveOrderDetails(com.z2systems.schemas.store.RetrieveOrderDetailsRequest request)*
     */
    public com.z2systems.schemas.store.RetrieveOrderDetailsResponse retrieveOrderDetails(com.z2systems.schemas.store.RetrieveOrderDetailsRequest request) { 
        LOG.info("Executing operation retrieveOrderDetails");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.RetrieveOrderDetailsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#removeProductOption(com.z2systems.schemas.store.RemoveProductOptionRequest request)*
     */
    public com.z2systems.schemas.store.RemoveProductOptionResponse removeProductOption(com.z2systems.schemas.store.RemoveProductOptionRequest request) { 
        LOG.info("Executing operation removeProductOption");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.RemoveProductOptionResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#updateCategory(com.z2systems.schemas.store.UpdateCategoryRequest request)*
     */
    public com.z2systems.schemas.store.UpdateCategoryResponse updateCategory(com.z2systems.schemas.store.UpdateCategoryRequest request) { 
        LOG.info("Executing operation updateCategory");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.UpdateCategoryResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#createProductOption(com.z2systems.schemas.store.CreateProductOptionRequest request)*
     */
    public com.z2systems.schemas.store.CreateProductOptionResponse createProductOption(com.z2systems.schemas.store.CreateProductOptionRequest request) { 
        LOG.info("Executing operation createProductOption");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.CreateProductOptionResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#updateProductOption(com.z2systems.schemas.store.UpdateProductOptionRequest request)*
     */
    public com.z2systems.schemas.store.UpdateProductOptionResponse updateProductOption(com.z2systems.schemas.store.UpdateProductOptionRequest request) { 
        LOG.info("Executing operation updateProductOption");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.UpdateProductOptionResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#retrieveProduct(com.z2systems.schemas.store.RetrieveProductRequest request)*
     */
    public com.z2systems.schemas.store.RetrieveProductResponse retrieveProduct(com.z2systems.schemas.store.RetrieveProductRequest request) { 
        LOG.info("Executing operation retrieveProduct");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.RetrieveProductResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#createProduct(com.z2systems.schemas.store.CreateProductRequest request)*
     */
    public com.z2systems.schemas.store.CreateProductResponse createProduct(com.z2systems.schemas.store.CreateProductRequest request) { 
        LOG.info("Executing operation createProduct");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.CreateProductResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#removeCatalog(com.z2systems.schemas.store.RemoveCatalogRequest request)*
     */
    public com.z2systems.schemas.store.RemoveCatalogResponse removeCatalog(com.z2systems.schemas.store.RemoveCatalogRequest request) { 
        LOG.info("Executing operation removeCatalog");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.RemoveCatalogResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#removeProductImage(com.z2systems.schemas.store.RemoveProductImageRequest request)*
     */
    public com.z2systems.schemas.store.RemoveProductImageResponse removeProductImage(com.z2systems.schemas.store.RemoveProductImageRequest request) { 
        LOG.info("Executing operation removeProductImage");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.RemoveProductImageResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#updateProduct(com.z2systems.schemas.store.UpdateProductRequest request)*
     */
    public com.z2systems.schemas.store.UpdateProductResponse updateProduct(com.z2systems.schemas.store.UpdateProductRequest request) { 
        LOG.info("Executing operation updateProduct");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.UpdateProductResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#uploadProductImage(com.z2systems.schemas.store.UploadProductImageRequest request)*
     */
    public com.z2systems.schemas.store.UploadProductImageResponse uploadProductImage(com.z2systems.schemas.store.UploadProductImageRequest request) { 
        LOG.info("Executing operation uploadProductImage");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.UploadProductImageResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#removeProductFromCatalog(com.z2systems.schemas.store.RemoveProductFromCatalogRequest request)*
     */
    public com.z2systems.schemas.store.RemoveProductFromCatalogResponse removeProductFromCatalog(com.z2systems.schemas.store.RemoveProductFromCatalogRequest request) { 
        LOG.info("Executing operation removeProductFromCatalog");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.RemoveProductFromCatalogResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#createCategory(com.z2systems.schemas.store.CreateCategoryRequest request)*
     */
    public com.z2systems.schemas.store.CreateCategoryResponse createCategory(com.z2systems.schemas.store.CreateCategoryRequest request) { 
        LOG.info("Executing operation createCategory");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.CreateCategoryResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#createShoppingCart(com.z2systems.schemas.store.CreateShoppingCartRequest request)*
     */
    public com.z2systems.schemas.store.CreateShoppingCartResponse createShoppingCart(com.z2systems.schemas.store.CreateShoppingCartRequest request) { 
        LOG.info("Executing operation createShoppingCart");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.CreateShoppingCartResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#addOrUpdateCustomerToShoppingCart(com.z2systems.schemas.store.AddOrUpdateCustomerToShoppingCartRequest request)*
     */
    public com.z2systems.schemas.store.AddOrUpdateCustomerToShoppingCartResponse addOrUpdateCustomerToShoppingCart(com.z2systems.schemas.store.AddOrUpdateCustomerToShoppingCartRequest request) { 
        LOG.info("Executing operation addOrUpdateCustomerToShoppingCart");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.AddOrUpdateCustomerToShoppingCartResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#removeProduct(com.z2systems.schemas.store.RemoveProductRequest request)*
     */
    public com.z2systems.schemas.store.RemoveProductResponse removeProduct(com.z2systems.schemas.store.RemoveProductRequest request) { 
        LOG.info("Executing operation removeProduct");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.RemoveProductResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#updateCatalog(com.z2systems.schemas.store.UpdateCatalogRequest request)*
     */
    public com.z2systems.schemas.store.UpdateCatalogResponse updateCatalog(com.z2systems.schemas.store.UpdateCatalogRequest request) { 
        LOG.info("Executing operation updateCatalog");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.UpdateCatalogResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#listShippingMethods(com.z2systems.schemas.store.ListShippingMethodsRequest request)*
     */
    public com.z2systems.schemas.store.ListShippingMethodsResponse listShippingMethods(com.z2systems.schemas.store.ListShippingMethodsRequest request) { 
        LOG.info("Executing operation listShippingMethods");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.ListShippingMethodsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#createCatalog(com.z2systems.schemas.store.CreateCatalogRequest request)*
     */
    public com.z2systems.schemas.store.CreateCatalogResponse createCatalog(com.z2systems.schemas.store.CreateCatalogRequest request) { 
        LOG.info("Executing operation createCatalog");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.CreateCatalogResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#addProductToCatalog(com.z2systems.schemas.store.AddProductToCatalogRequest request)*
     */
    public com.z2systems.schemas.store.AddProductToCatalogResponse addProductToCatalog(com.z2systems.schemas.store.AddProductToCatalogRequest request) { 
        LOG.info("Executing operation addProductToCatalog");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.AddProductToCatalogResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#retrieveStorePurchaseStats(com.z2systems.schemas.store.RetrieveStorePurchaseStatsRequest request)*
     */
    public com.z2systems.schemas.store.RetrieveStorePurchaseStatsResponse retrieveStorePurchaseStats(com.z2systems.schemas.store.RetrieveStorePurchaseStatsRequest request) { 
        LOG.info("Executing operation retrieveStorePurchaseStats");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.RetrieveStorePurchaseStatsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#addOrUpdateShippingMethodToShoppingCart(com.z2systems.schemas.store.AddOrUpdateShippingMethodToShoppingCartRequest request)*
     */
    public com.z2systems.schemas.store.AddOrUpdateShippingMethodToShoppingCartResponse addOrUpdateShippingMethodToShoppingCart(com.z2systems.schemas.store.AddOrUpdateShippingMethodToShoppingCartRequest request) { 
        LOG.info("Executing operation addOrUpdateShippingMethodToShoppingCart");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.AddOrUpdateShippingMethodToShoppingCartResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.z2systems.schemas.neonws.StoreService#listCategories(com.z2systems.schemas.store.ListCategoriesRequest request)*
     */
    public com.z2systems.schemas.store.ListCategoriesResponse listCategories(com.z2systems.schemas.store.ListCategoriesRequest request) { 
        LOG.info("Executing operation listCategories");
        System.out.println(request);
        try {
            com.z2systems.schemas.store.ListCategoriesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
