package com.z2systems.schemas.neonws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-24T17:30:59.718Z
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://www.z2systems.com/schemas/neonws/", name = "StoreService")
@XmlSeeAlso({com.z2systems.schemas.membership.ObjectFactory.class, com.z2systems.schemas.common.ObjectFactory.class, com.z2systems.schemas.account.ObjectFactory.class, com.z2systems.schemas.donation.ObjectFactory.class, com.z2systems.schemas.store.ObjectFactory.class, ObjectFactory.class, com.z2systems.schemas.event.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StoreService {

    @WebResult(name = "listOrdersResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.ListOrdersResponse listOrders(
            @WebParam(partName = "request", name = "listOrdersRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.ListOrdersRequest request
    );

    @WebResult(name = "removeItemFromShoppingCartResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.RemoveItemFromShoppingCartResponse removeItemFromShoppingCart(
            @WebParam(partName = "request", name = "removeItemFromShoppingCartRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.RemoveItemFromShoppingCartRequest request
    );

    @WebResult(name = "listProductOptionsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.ListProductOptionsResponse listProductOptions(
            @WebParam(partName = "request", name = "listProductOptionsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.ListProductOptionsRequest request
    );

    @WebResult(name = "removeCategoryResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.RemoveCategoryResponse removeCategory(
            @WebParam(partName = "request", name = "removeCategoryRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.RemoveCategoryRequest request
    );

    @WebResult(name = "listCatalogsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.ListCatalogsResponse listCatalogs(
            @WebParam(partName = "request", name = "listCatalogsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.ListCatalogsRequest request
    );

    @WebResult(name = "listProductImagesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.ListProductImagesResponse listProductImages(
            @WebParam(partName = "request", name = "listProductImagesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.ListProductImagesRequest request
    );

    @WebResult(name = "addOrUpdateShippingAddressToShoppingCartResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.AddOrUpdateShippingAddressToShoppingCartResponse addOrUpdateShippingAddressToShoppingCart(
            @WebParam(partName = "request", name = "addOrUpdateShippingAddressToShoppingCartRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.AddOrUpdateShippingAddressToShoppingCartRequest request
    );

    @WebResult(name = "listProductsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.ListProductsResponse listProducts(
            @WebParam(partName = "request", name = "listProductsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.ListProductsRequest request
    );

    @WebResult(name = "retrieveShoppingCartSummaryResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.RetrieveShoppingCartSummaryResponse retrieveShoppingCartSummary(
            @WebParam(partName = "request", name = "retrieveShoppingCartSummaryRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.RetrieveShoppingCartSummaryRequest request
    );

    @WebResult(name = "retrieveReceiptResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.RetrieveReceiptResponse retrieveReceipt(
            @WebParam(partName = "request", name = "retrieveReceiptRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.RetrieveReceiptRequest request
    );

    @WebResult(name = "checkoutResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.CheckoutResponse checkout(
            @WebParam(partName = "request", name = "checkoutRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.CheckoutRequest request
    );

    @WebResult(name = "addItemToShoppingCartResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.AddItemToShoppingCartResponse addItemToShoppingCart(
            @WebParam(partName = "request", name = "addItemToShoppingCartRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.AddItemToShoppingCartRequest request
    );

    @WebResult(name = "retrieveOrderDetailsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.RetrieveOrderDetailsResponse retrieveOrderDetails(
            @WebParam(partName = "request", name = "retrieveOrderDetailsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.RetrieveOrderDetailsRequest request
    );

    @WebResult(name = "removeProductOptionResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.RemoveProductOptionResponse removeProductOption(
            @WebParam(partName = "request", name = "removeProductOptionRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.RemoveProductOptionRequest request
    );

    @WebResult(name = "updateCategoryResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.UpdateCategoryResponse updateCategory(
            @WebParam(partName = "request", name = "updateCategoryRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.UpdateCategoryRequest request
    );

    @WebResult(name = "createProductOptionResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.CreateProductOptionResponse createProductOption(
            @WebParam(partName = "request", name = "createProductOptionRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.CreateProductOptionRequest request
    );

    @WebResult(name = "updateProductOptionResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.UpdateProductOptionResponse updateProductOption(
            @WebParam(partName = "request", name = "updateProductOptionRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.UpdateProductOptionRequest request
    );

    @WebResult(name = "retrieveProductResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.RetrieveProductResponse retrieveProduct(
            @WebParam(partName = "request", name = "retrieveProductRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.RetrieveProductRequest request
    );

    @WebResult(name = "createProductResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.CreateProductResponse createProduct(
            @WebParam(partName = "request", name = "createProductRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.CreateProductRequest request
    );

    @WebResult(name = "removeCatalogResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.RemoveCatalogResponse removeCatalog(
            @WebParam(partName = "request", name = "removeCatalogRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.RemoveCatalogRequest request
    );

    @WebResult(name = "removeProductImageResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.RemoveProductImageResponse removeProductImage(
            @WebParam(partName = "request", name = "removeProductImageRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.RemoveProductImageRequest request
    );

    @WebResult(name = "updateProductResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.UpdateProductResponse updateProduct(
            @WebParam(partName = "request", name = "updateProductRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.UpdateProductRequest request
    );

    @WebResult(name = "uploadProductImageResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.UploadProductImageResponse uploadProductImage(
            @WebParam(partName = "request", name = "uploadProductImageRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.UploadProductImageRequest request
    );

    @WebResult(name = "removeProductFromCatalogResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.RemoveProductFromCatalogResponse removeProductFromCatalog(
            @WebParam(partName = "request", name = "removeProductFromCatalogRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.RemoveProductFromCatalogRequest request
    );

    @WebResult(name = "createCategoryResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.CreateCategoryResponse createCategory(
            @WebParam(partName = "request", name = "createCategoryRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.CreateCategoryRequest request
    );

    @WebResult(name = "createShoppingCartResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.CreateShoppingCartResponse createShoppingCart(
            @WebParam(partName = "request", name = "createShoppingCartRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.CreateShoppingCartRequest request
    );

    @WebResult(name = "addOrUpdateCustomerToShoppingCartResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.AddOrUpdateCustomerToShoppingCartResponse addOrUpdateCustomerToShoppingCart(
            @WebParam(partName = "request", name = "addOrUpdateCustomerToShoppingCartRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.AddOrUpdateCustomerToShoppingCartRequest request
    );

    @WebResult(name = "removeProductResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.RemoveProductResponse removeProduct(
            @WebParam(partName = "request", name = "removeProductRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.RemoveProductRequest request
    );

    @WebResult(name = "updateCatalogResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.UpdateCatalogResponse updateCatalog(
            @WebParam(partName = "request", name = "updateCatalogRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.UpdateCatalogRequest request
    );

    @WebResult(name = "listShippingMethodsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.ListShippingMethodsResponse listShippingMethods(
            @WebParam(partName = "request", name = "listShippingMethodsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.ListShippingMethodsRequest request
    );

    @WebResult(name = "createCatalogResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.CreateCatalogResponse createCatalog(
            @WebParam(partName = "request", name = "createCatalogRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.CreateCatalogRequest request
    );

    @WebResult(name = "addProductToCatalogResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.AddProductToCatalogResponse addProductToCatalog(
            @WebParam(partName = "request", name = "addProductToCatalogRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.AddProductToCatalogRequest request
    );

    @WebResult(name = "retrieveStorePurchaseStatsResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.RetrieveStorePurchaseStatsResponse retrieveStorePurchaseStats(
            @WebParam(partName = "request", name = "retrieveStorePurchaseStatsRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.RetrieveStorePurchaseStatsRequest request
    );

    @WebResult(name = "addOrUpdateShippingMethodToShoppingCartResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.AddOrUpdateShippingMethodToShoppingCartResponse addOrUpdateShippingMethodToShoppingCart(
            @WebParam(partName = "request", name = "addOrUpdateShippingMethodToShoppingCartRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.AddOrUpdateShippingMethodToShoppingCartRequest request
    );

    @WebResult(name = "listCategoriesResponse", targetNamespace = "http://www.z2systems.com/schemas/neonws/", partName = "response")
    @WebMethod
    public com.z2systems.schemas.store.ListCategoriesResponse listCategories(
            @WebParam(partName = "request", name = "listCategoriesRequest", targetNamespace = "http://www.z2systems.com/schemas/neonws/")
                    com.z2systems.schemas.store.ListCategoriesRequest request
    );
}
